### ISSUE TITLE
Switch to using https for connection to Couchbase cluster

### ISSUE THREAD

**Issue by bitdba88** [blakelead/couchbase_exporter#34]
Change to default to https://localhost:18091 instead of the non secure port since the code is pushing a password in the connection. Need to also add the ability to change TLS setting to ignore self signed certificates.  

You can check my code on the fork https://github.com/bitdba88/couchbase_exporter if that makes it easier.

**Comment by blakelead** [comment]
Hey @bitdba88 ,

That's a big contribution thanks a lot! If you don't mind I'll add your additions (with minor modifications) and acknowledge your contribution in the README.

After checking your code I did not understand the purpose of the second  dbURI. Could you tell me more about that ?

**Comment by bitdba88** [comment]
That was so in a multi node environment if the first node did not respond it will move to another node.  I need to double check because when I have run Coucbbase in a cluster I have always only gone to one node to see everything going on for that cluster.  But I read one of questions that said you need to run one connection per node.  I don't think that is true but I will need to test to see what is being return.  When I tested you're 0.7.0 code I could see all nodes in the cluster metrics return but will need to double check  tomorrow.

**Comment by bitdba88** [comment]
It was from this answer that I questioned if the changes for the second URI was required.

https://github.com/leansys-team/couchbase_exporter/issues/29

**Comment by bitdba88** [comment]
I think I was looking at a different exporter before I forked yours.  In another exporter it shows all the nodes are healthy from a single scrape.  https://github.com/totvslabs/couchbase-exporter.git. but this code is expecting to run on every node like node exporter.  I can live with that.  Do you have the prometheus setup your using?  I don't see that in the examples.  I'm going to remove the second URI from my fork as it has no benefit.

**Comment by blakelead** [comment]
I'm using Ansible to install Prometheus and that is the configuration template associated with it (I removed the parts unrelated to Couchbase):

```yaml
global:
  scrape_interval: 10s
  scrape_timeout: 5s # must be lower than scrape_interval
  evaluation_interval: 5s

rule_files:
- ./couchbase-rules.yml

scrape_configs:
- job_name: Couchbase
  static_configs:
{% for host in groups['couchbase'] %}
  - targets: ['{{ hostvars[host].ansible_host }}:{{ couchbase_exporter_port }}']
    labels:
      instance: '{{ hostvars[host].inventory_hostname }}'
      host: '{{ hostvars[host].ansible_host }}'
      environment: '{{ environment_name }}'
{% endfor %}
```

And the `./couchbase-rules.yml` file is actually the one you can find in `examples` directory.

I proposed earlier to copy your code into the exporter and mention you in the readme, but if you prefer to submit a PR that's great too!
